// キービジュアル計画 — key → Commons検索クエリ（または直接ファイル指定）
// key 規約: "cat:<カテゴリid>" | "ind:<業界slug>" | "occ:<職種slug>"
// SPA側フォールバック: occ:<slug> → cat:<categoryId> → なし（画像なしでも成立するデザイン）
// 目視検証で不適切だった key は { file:"File:～" } で直接指定して差し替える。
export default {
  // ---- 職種カテゴリ 11 ----
  "cat:occ_business":     { file: "File:クロスタワー前、新入社員たちのグループ.jpg" },
  "cat:occ_office":       { file: "File:Helloquence-61189.jpg" },
  "cat:occ_it":           { q: "programming source code laptop" },
  "cat:occ_creative":     { q: "design studio camera production" },
  "cat:occ_service":      { q: "shopping arcade Japan shotengai" },
  "cat:occ_medical":      { q: "hospital corridor Japan" },
  "cat:occ_estate":       { q: "construction site tower crane Japan" },
  "cat:occ_technical":    { file: "File:001 Car factory assembly line - Opel factory in Gliwice, Poland.jpg" },
  "cat:occ_education":    { file: "File:Hitane Elementary School classroom 2.jpg" },
  "cat:occ_professional": { q: "law books library statute" },
  "cat:occ_public":       { q: "Kasumigaseki government buildings Tokyo" },
  // ---- 業界 16 ----
  "ind:it":            { q: "datacenter server racks" },
  "ind:web":           { q: "person working laptop cafe" },
  "ind:advertising":   { q: "Shibuya crossing billboards neon" },
  "ind:finance":       { q: "Tokyo Stock Exchange trading floor" },
  "ind:real-estate":   { q: "Tokyo residential buildings apartments" },
  "ind:construction":  { q: "construction workers building site Japan" },
  "ind:manufacturing": { q: "industrial factory Japan plant" },
  "ind:retail":        { q: "supermarket aisle Japan store" },
  "ind:food":          { q: "ramen shop Japan restaurant" },
  "ind:logistics":     { file: "File:Container ship MSC Tokyo - IMO 9318046 - moored at Container Terminal Burchardkai, Hamburg-9496.jpg" },
  "ind:medical":       { file: "File:20080312-StLukesInternationalHospital.jpg" },
  "ind:care":          { q: "nursing home elderly care" },
  "ind:beauty":        { q: "hair salon interior" },
  "ind:education":     { q: "university lecture hall Japan" },
  "ind:hr":            { file: "File:2024 Fire Hire in Sacramento (53513296369).jpg" },
  "ind:consulting":    { q: "conference room business meeting" },
  // ---- 主要職種 22 ----
  "occ:sales":            { q: "business handshake meeting" },
  "occ:office-admin":     { file: "File:Helloquence-61189.jpg" },
  "occ:accounting":       { file: "File:Latte and calculator.jpg" },
  "occ:hr":               { file: "File:2024 Fire Hire in Sacramento (53513414015).jpg" },
  "occ:marketing":        { file: "File:20170403-AMS-LSC-1208 (33763989742).jpg" },
  "occ:web-marketing":    { file: "File:Google analytics phone (Unsplash).jpg" },
  "occ:engineer":         { file: "File:Software Developer at Work.jpg" },
  "occ:web-designer":     { file: "File:Responsive-web-design-devices.jpg" },
  "occ:consultant":       { file: "File:Ejay presenting a business seminar.jpg" },
  "occ:retail-sales":     { file: "File:Itoya (20076839120).jpg" },
  "occ:food-service":     { q: "restaurant kitchen chef cooking" },
  "occ:construction":     { q: "construction worker helmet site" },
  "occ:real-estate":      { q: "estate agent window advertisements" },
  "occ:nurse":            { file: "File:Nurse shows a heart sign to a child during a medical visit in a bright room.jpg" },
  "occ:medical-staff":    { q: "hospital reception desk" },
  "occ:manufacturing":    { q: "factory worker assembly Japan" },
  "occ:logistics":        { q: "warehouse forklift pallets" },
  "occ:driver":           { file: "File:Yamato delivery electrick truck, Hino.jpg" },
  "occ:education":        { file: "File:Better quality learning in a safe environment (8423292169).jpg" },
  "occ:beauty":           { file: "File:DZ6 0589 A barber carefully trims a customers hair inside a cozy cluttered shop adorned with an American flag and various tools.jpg" },
  "occ:it-support":       { q: "computer repair technician support" },
  // ---- 記事ヒーロー用 6 ----
  "art:calendar": { file: "File:EFTA00003027-Beach-House - Cluttered desk with a calendar filled with handwritten notes pens sticky notes and a calculator.jpg" },
  "art:study":    { file: "File:Pen-writing-notes-studying.jpg" },
  "art:resume":   { file: "File:Person writing in a notebook while sitting at a desk.jpg" },
  "art:rural":    { file: "File:Nagano Matsukawa.jpg" },
};
