// キービジュアル計画 — key → Commons検索クエリ（または直接ファイル指定）
// key 規約: "cat:<カテゴリid>" | "ind:<業界slug>" | "occ:<職種slug>"
// SPA側フォールバック: occ:<slug> → cat:<categoryId> → なし（画像なしでも成立するデザイン）
// 目視検証で不適切だった key は { file:"File:～" } で直接指定して差し替える。
export default {
  // ---- 職種カテゴリ 11 ----
  "cat:occ_business":     { file: "File:クロスタワー前、新入社員たちのグループ.jpg" },
  "cat:occ_office":       { alias: "jp:otemachi" },
  "cat:occ_it":           { alias: "jp:akihabara" },
  "cat:occ_creative":     { alias: "jp:tvstudio" },
  "cat:occ_service":      { q: "shopping arcade Japan shotengai" },
  "cat:occ_medical":      { alias: "jp:hospital2" },
  "cat:occ_estate":       { q: "construction site tower crane Japan" },
  "cat:occ_technical":    { alias: "jp:plant" },
  "cat:occ_education":    { file: "File:Hitane Elementary School classroom 2.jpg" },
  "cat:occ_professional": { alias: "jp:court" },
  "cat:occ_public":       { q: "Kasumigaseki government buildings Tokyo" },
  // ---- 業界 16 ----
  "ind:it":            { alias: "jp:akihabara" },
  "ind:web":           { alias: "jp:umeda" },
  "ind:advertising":   { q: "Shibuya crossing billboards neon" },
  "ind:finance":       { q: "Tokyo Stock Exchange trading floor" },
  "ind:real-estate":   { q: "Tokyo residential buildings apartments" },
  "ind:construction":  { alias: "jp:construction" },
  "ind:manufacturing": { q: "industrial factory Japan plant" },
  "ind:retail":        { q: "supermarket aisle Japan store" },
  "ind:food":          { q: "ramen shop Japan restaurant" },
  "ind:logistics":     { alias: "jp:aomi" },
  "ind:medical":       { file: "File:20080312-StLukesInternationalHospital.jpg" },
  "ind:care":          { alias: "jp:hospital2" },
  "ind:beauty":        { alias: "jp:barber" },
  "ind:education":     { q: "university lecture hall Japan" },
  "ind:hr":            { alias: "jp:bigsight" },
  "ind:consulting":    { alias: "jp:otemachi" },
  // ---- 主要職種 22 ----
  "occ:sales":            { alias: "jp:otemachi" },
  "occ:office-admin":     { alias: "jp:otemachi" },
  "occ:accounting":       { alias: "jp:court" },
  "occ:hr":               { alias: "jp:bigsight" },
  "occ:marketing":        { alias: "jp:bigsight" },
  "occ:web-marketing":    { alias: "jp:umeda" },
  "occ:engineer":         { alias: "jp:akihabara" },
  "occ:web-designer":     { alias: "jp:umeda" },
  "occ:consultant":       { alias: "jp:bigsight" },
  "occ:retail-sales":     { file: "File:Itoya (20076839120).jpg" },
  "occ:food-service":     { alias: "jp:ramen" },
  "occ:construction":     { alias: "jp:construction" },
  "occ:real-estate":      { alias: "ind:real-estate" },
  "occ:nurse":            { alias: "jp:hospital2" },
  "occ:medical-staff":    { alias: "jp:hospital2" },
  "occ:manufacturing":    { alias: "jp:yokkaichi" },
  "occ:logistics":        { alias: "jp:aomi" },
  "occ:driver":           { file: "File:Yamato delivery electrick truck, Hino.jpg" },
  "occ:education":        { alias: "cat:occ_education" },
  "occ:beauty":           { alias: "jp:barber" },
  "occ:it-support":       { alias: "jp:akihabara" },
  // ---- 記事ヒーロー用 6 ----
  "art:calendar": { alias: "jp:riceterrace" },
  "art:study":    { alias: "jp:university" },
  "art:resume":   { alias: "jp:otemachi" },
  "art:rural":    { file: "File:Nagano Matsukawa.jpg" },
  // ---- 日本国内マーキー用（jp: プレフィックス。マーキーは国内画像に限定する） ----
  "jp:supermarket":  { file: "File:Interior of Supermarket in Japan 01.jpg" },
  "jp:construction": { file: "File:Construction works Japan, Osaka.jpg" },
  "jp:university":   { file: "File:Students walking towards Komaba Campus, University of Tokyo.jpg" },
  "jp:ramen":        { file: "File:Kyushu Jangara Ramen, Akihabara - Chefs in the open kitchen facing to the counter (2006-07-08 17.03.17 by Marufish).jpg" },
  "jp:shinkansen":   { file: "File:Shinkansen platform at Tokyo Station 22.jpg" },
  "jp:tobi":         { file: "File:Workers in tobi pants.jpg" },
  "jp:barber":       { file: "File:Barber Tatsumiya in Kahoku, Yamagata 2009-10-23.jpg" },
  "jp:umeda":      { file: "File:Evening cityscape of Osaka.jpg" },
  "jp:riceterrace":{ file: "File:Fukuoka-Tsuzura Rice Terrace in an Early Summer-xl.jpg" },
  "jp:plant":      { file: "File:Okayama-Night view of the industrial plant in Mizushima-xl.jpg" },
  "jp:yokkaichi":  { file: "File:Factory buildings in Yokkaichi at night; 2016.jpg" },
  "jp:court":     { file: "File:Tokyo District Court Tachikawa.jpg" },
  "jp:tvstudio":  { file: "File:San-in Chuo Television - Camera Operator.JPG" },
  "jp:hospital2": { file: "File:Sakuramachi hospital, Koganei 202512-1.jpg" },
  "jp:otemachi":  { file: "File:Chiyoda office buildings.jpg" },
  "jp:akihabara": { file: "File:Akihabara, electronics district.jpg" },
  "jp:bigsight":  { file: "File:Tokyo Big Sight at Night.jpg" },
  "jp:aomi":      { file: "File:Aomi container terminal.jpg" },
};